name: Static checks - misspell
on: push

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: egde-resource-mgr-'${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: ubuntu-22.04
    env:
      SUMMARY_FILE: summary.log
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Remove vendor folder
        run: rm -rf vendor
      - name: Misspell
        uses: PelionIoT/actions/.github/actions/misspell@main
        with:
          exceptions: "mosquitto"      
